const curiosidad=[
    {
        id:1,
        texto:"¿Sabes que la palabra perfume procede del latín per “por” y fumare “a través del humo”? Hacía referencia a la sustancia aromática que desprendía un humo fragante al ser quemada.",
    },
    {
        id:2,
        texto:"¿Adivinas qué civilización fue la que inventó el perfume? Pues nada más y nada menos que los sumerios, 3500 años antes de Cristo. También desarrollaron ungüentos varios.",
    },
    {
        id:3,
        texto:"Los egipcios fueron los primeros en perfumarse con regularidad. Hacia el año 1558 antes de Cristo se convirtió en una auténtica obsesión nacional. De hecho Cleopatra era una artista del perfume.",
    },
    {
        id:4,
        texto:"Perfumarse también es de chicos duros y es que los gladiadores antes de salir a combatir se echaban una loción aromática diferente en varias partes de su cuerpo. En la antigua Roma la obsesión llegó a ser tal, que tanto hombres como mujeres tomaban baños de perfume.",
    },
    {
        id:5,
        texto:"En el palacio de Luis XV ya hicieron sus pinitos con los ambientadores y es que los criados bañaban a las palomas en distintos perfumes y las liberaban durante las fiestas. Así, esparcían los aromas, allá por donde volasen. Debes saber que en esa época no se lavaban mucho (o nada) y para disimular el mal olor, se perfumaban muchísimo.",
    },
    {
        id:6,
        texto:"Como sabrás, el PH de la piel mide su acidez. Por lo general, no cambia mucho de una persona a otra pero esta mínima diferencia es suficiente para que uno o varios de los ingredientes que conforman la fragancia, interactúe de manera diferente en cada piel.",
    },
    {
        id:7,
        texto:"¿Dura lo mismo un perfume en una piel que en otra? Las pieles morenas suelen tender a grasas y es esta grasa que produce el organismo la que, en contacto con los aceites del perfume, hace que el aroma sea más intenso. A estas personas les vienen bien los perfumes intensos, florales o cítricos, a base de civeta, tabaco, almizcle, ámbar, incienso y rosas. Lo contrario ocurre con las pieles blancas, que suelen ser secas. Para estas pieles, lo mejor son los aromas frescos y estimulantes.",
    },
    {
        id:8,
        texto:"¿Sabes que las españolas somos las que más nos perfumamos de Europa? Nos siguen las italianas y las francesas.",
    },
    {
        id:9,
        texto:"¿Qué es una eau de cologne? Es una solución compuesta por alrededor de un 3% de perfume en una base de alcohol y agua. Es el aroma más ligero y menos duradero.",
    },
    {
        id:10,
        texto:"La eau de toilette es una solución compuesta por entre un 3% y un 8% en una base de agua o de alcohol. Menos concentrada que la eau de parfum, suele ser utilizada para crear una versión más suave de una fragancia.",
    },
    {
        id:11,
        texto:"Una eau de parfum es una solución de perfume en alcohol conteniendo entre un 10% y 15% de perfume.",
    },
    {
        id:12,
        texto:"La fragancia que contiene entre un 20% y 50% de perfume sería calificada como perfume. Es la opción más duradera e intensa, y la más cara.",
    },
];

const pacoArray=[
    {
        id:1,
        imagen:'./images/pacoRabanne/paco_rabanne_1_million_eau_de_toilette.jpg',
        marca:'Paco Rabanne',
        flanker:'ONE MILLON EDT',
        precio:69250,
    },
    {
        id:2,
        imagen:'./images/pacoRabanne/fame-paco-rabanne.png',
        marca:'Paco Rabanne',
        flanker:'FAME EDP REFILLABLE',
        precio:59600,
    },
    {
        id:3,
        imagen:'./images/pacoRabanne/invictus-platinum-edp.jpg',
        marca:'Paco Rabanne',
        flanker:'INVICTUS PLATINUM EDP',
        precio:52550,
    },
    {
        id:4,
        imagen:'./images/pacoRabanne/phantom.jpg',
        marca:'Paco Rabanne',
        flanker:'PHANTOM EDT',
        precio:64550,
    },
    {
        id:5,
        imagen:'./images/pacoRabanne/fame-paco-rabanne.png',
        marca:'Paco Rabanne',
        flanker:'FAME EDP',
        precio:48500,
    },
    {
        id:6,
        imagen:'./images/pacoRabanne/olympea.jpg',
        marca:'Paco Rabanne',
        flanker:'OLYMPEA SOLAR EDP',
        precio:60250,
    },
    {
        id:7,
        imagen:'./images/pacoRabanne/paco-rabanne-olympea-blossom.jpg',
        marca:'Paco Rabanne',
        flanker:'OLYMPEA BLOSSOM EDP',
        precio:57400,
    },
    {
        id:8,
        imagen:'./images/pacoRabanne/1-MILLION-ELIXIR-PARFUM-INTENSE-PACO-RABANNE.jpg',
        marca:'Paco Rabanne',
        flanker:'ONE MILLON ELIXIR PARFUM INTENSE',
        precio:57300,
    },
    {
        id:9,
        imagen:'./images/pacoRabanne/invictus-victory-edlim.jpg',
        marca:'Paco Rabanne',
        flanker:'INVICTUS VICTORY EDP ED. LIMITADA',
        precio:79600,
    },
    {
        id:10,
        imagen:'./images/pacoRabanne/invictus-edt.jpg',
        marca:'Paco Rabanne',
        flanker:'INVICTUS EDT',
        precio:47750,
    },
    {
        id:11,
        imagen:'./images/pacoRabanne/lady-fabulous.jpg',
        marca:'Paco Rabanne',
        flanker:'LADY MILLON FABULOUS EDP',
        precio:60250,
    },
    {
        id:12,
        imagen:'./images/pacoRabanne/lady-million.jpg',
        marca:'Paco Rabanne',
        flanker:'LADY MILLON EDP',
        precio:36750,
    },
    {
        id:13,
        imagen:'./images/pacoRabanne/invictus-victory-edlim.jpg',
        marca:'Paco Rabanne',
        flanker:'INVICTUS VICTORY EDP',
        precio:46600,
    },
    {
        id:14,
        imagen:'./images/pacoRabanne/1-MILLION-ELIXIR-PARFUM-INTENSE-PACO-RABANNE.jpg',
        marca:'Paco Rabanne',
        flanker:'ONE MILLON EDP',
        precio:46600,
    },
    {
        id:15,
        imagen:'./images/pacoRabanne/fame-refill.jpg',
        marca:'Paco Rabanne',
        flanker:'FAME EDP REFILL',
        precio:68550,
    },
    {
        id:16,
        imagen:'./images/pacoRabanne/invictus-elixir-parfum.jpg',
        marca:'Paco Rabanne',
        flanker:'INVICTUS VICTORY ELIXIR PARFUM',
        precio:57300,
    },
    {
        id:17,
        imagen:'./images/pacoRabanne/olympea-flora.jpg',
        marca:'Paco Rabanne',
        flanker:'OLYMPEA FLORA EDP',
        precio:60250,
    },
    {
        id:18,
        imagen:'./images/pacoRabanne/D_NQ_NP_888509-MLA53004791334_122022-V.jpg',
        marca:'Paco Rabanne',
        flanker:'INVICTUS EDT',
        precio:47750,
    },
    {
        id:19,
        imagen:'./images/pacoRabanne/phantom-recarga.jpg',
        marca:'Paco Rabanne',
        flanker:'PHANTOM EDT REFILL',
        precio:64550,
    },
    {
        id:20,
        imagen:'./images/pacoRabanne/paco_rabanne_pour_homme.jpg',
        marca:'Paco Rabanne',
        flanker:'PACO RABANNE POUR HOMME EDT',
        precio:38550,
    },
    {
        id:21,
        imagen:'./images/pacoRabanne/pure-xs.jpg',
        marca:'Paco Rabanne',
        flanker:'PURE XS EDT',
        precio:40600,
    }
];

const chArray=[
    {
        id:1,
        imagen:'./images/ch/212-men-edt.webp',
        marca:'Carolina Herrera',
        flanker:'212 MEN EDT',
        precio:65200,
    },
    {
        id:2,
        imagen:'./images/ch/212-vip-men-edt.webp',
        marca:'Carolina Herrera',
        flanker:'212 VIP MEN EDT',
        precio:65200,
    },
    {
        id:3,
        imagen:'./images/ch/212-vip-men-black-edp.webp',
        marca:'Carolina Herrera',
        flanker:'212 VIP MEN BLACK EDP',
        precio:46050,
    },
    {
        id:4,
        imagen:'./images/ch/very-good-girl-glam-parfum.webp',
        marca:'Carolina Herrera',
        flanker:'VERY GOOD GIRL GLAM PARFUM',
        precio:59600,
    },
    {
        id:5,
        imagen:'./images/ch/good-girl-edp.webp',
        marca:'Carolina Herrera',
        flanker:'GOOD GIRL EDP',
        precio:59600,
    },
    {
        id:6,
        imagen:'./images/ch/bad-boy-le-parfum.webp',
        marca:'Carolina Herrera',
        flanker:'BAD BOY LE PARFUM',
        precio:53750,
    },
    {
        id:7,
        imagen:'./images/ch/212-vip-rose-edp.webp',
        marca:'Carolina Herrera',
        flanker:'212 VIP ROSE EDP',
        precio:56600,
    },
    {
        id:8,
        imagen:'./images/ch/212-heroes-for-her-edp.webp',
        marca:'Carolina Herrera',
        flanker:'212 HEROES FOR HER EDP',
        precio:54900,
    },
    {
        id:9,
        imagen:'./images/ch/212-vip-rose-edp-ed-lim.webp',
        marca:'Carolina Herrera',
        flanker:'212 VIP ROSE EDP ED. LIMITADA',
        precio:70750,
    },
    {
        id:10,
        imagen:'./images/ch/bad-boy-edt.webp',
        marca:'Carolina Herrera',
        flanker:'BAD BOY EDT',
        precio:48850,
    },
    {
        id:11,
        imagen:'./images/ch/212-edt.webp',
        marca:'Carolina Herrera',
        flanker:'212 EDT',
        precio:53650,
    },
    {
        id:12,
        imagen:'./images/ch/very-good-girl-edp.webp',
        marca:'Carolina Herrera',
        flanker:'VERY GOOD GIRL EDP',
        precio:62600,
    },
    {
        id:13,
        imagen:'./images/ch/good-girl-supreme-edp.webp',
        marca:'Carolina Herrera',
        flanker:'GOOD GIRL SUPREME EDP',
        precio:62600,
    },
    {
        id:14,
        imagen:'./images/ch/212-heroes-edt.webp',
        marca:'Carolina Herrera',
        flanker:'212 HEROES EDT',
        precio:44550,
    },
    {
        id:15,
        imagen:'./images/ch/ch-men-edt.webp',
        marca:'Carolina Herrera',
        flanker:'CH MEN EDT',
        precio:31800,
    },
    {
        id:16,
        imagen:'./images/ch/bad-boy-cobalt-edp.webp',
        marca:'Carolina Herrera',
        flanker:'BAD BOY COBALT EDP',
        precio:51300,
    },
    {
        id:17,
        imagen:'./images/ch/212-vip-men-black-love-ny-edp-ed-limitada.webp',
        marca:'Carolina Herrera',
        flanker:'212 VIP MEN BLACK LOVE NY EDP ED. LIMITADA',
        precio:38200,
    },
    {
        id:18,
        imagen:'./images/ch/212-heroes-edt-ed-limitada.webp',
        marca:'Carolina Herrera',
        flanker:'212 HEROES EDT ED. LIMITADA',
        precio:62350,
    },
    {
        id:19,
        imagen:'./images/ch/212-vip-rose-love-edp-ed-limitada.webp',
        marca:'Carolina Herrera',
        flanker:'212 VIP ROSE LOVE NY ED.LIMITADA',
        precio:48300,
    },
    {
        id:20,
        imagen:'./images/ch/212-vip-edp.webp',
        marca:'Carolina Herrera',
        flanker:'212 VIP EDP',
        precio:56600,
    },
    {
        id:21,
        imagen:'./images/ch/bad-boy-cobalt-edp-ed-limitada.webp',
        marca:'Carolina Herrera',
        flanker:'BAD BOY COBALT EDP ED. LIMITADA',
        precio:74400,
    },
    {
        id:22,
        imagen:'./images/ch/carolina-herrera-edp.webp',
        marca:'Carolina Herrera',
        flanker:'CAROLINA HERRERA EDP',
        precio:61400,
    },
    {
        id:23,
        imagen:'./images/ch/bad-boy-gold-fantasy-edt-ed-limitada.webp',
        marca:'Carolina Herrera',
        flanker:'BAD BOY GOLD FANTASY EDT ED. LIMITADA',
        precio:46400,
    },
    {
        id:24,
        imagen:'./images/ch/212-heroes-edt-regalo.webp',
        marca:'Carolina Herrera',
        flanker: '212 HEROES EDT + Regalo',
        precio:37200,
    },
    {
        id:25,
        imagen:'./images/ch/bad-boy-cobalt-edp-electrique.webp',
        marca:'Carolina Herrera',
        flanker:'BAD BOY COBALT EDP ELECTRIQUE',
        precio:51300,
    },
    {
        id:26,
        imagen:'./images/ch/212-heroes-edt-regalo-44550.webp',
        marca:'Carolina Herrera',
        flanker:'212 HEROES EDT',
        precio:44500,
    }
];

const diorArray=[
    {
        id:1,
        imagen:'./images/dior/sauvage-edt.webp',
        marca:'Dior',
        flanker:'SAUVAGE EDT',
        precio:72900,
    },
    {
        id:2,
        imagen:'./images/dior/sauvage-edp.webp',
        marca:'Dior',
        flanker:'SAUVAGE EDP',
        precio:59200,
    },
    {
        id:3,
        imagen:'./images/dior/homme-intense-edp.webp',
        marca:'Dior',
        flanker:'DIOR HOMME INSTENSE EDP',
        precio:59200,
    },
    {
        id:4,
        imagen:'./images/dior/jadore-edp.webp',
        marca:'Dior',
        flanker:'JADORE EDP',
        precio:60100,
    },
    {
        id:5,
        imagen:'./images/dior/miss-dior-edp.webp',
        marca:'Dior',
        flanker:'MISS DIOR EDP',
        precio:60100,
    },
    {
        id:6,
        imagen:'./images/dior/sauvage-parfum.webp',
        marca:'Dior',
        flanker:'SAUVAGE PARFUM',
        precio:71500,
    },
    {
        id:7,
        imagen:'./images/dior/escale-a-portofino-edt.webp',
        marca:'Dior',
        flanker:'ESCALE A PORTOFINO EDT',
        precio:52600,
    },
    {
        id:8,
        imagen:'./images/dior/dior-homme-new-edt.webp',
        marca:'Dior',
        flanker:'DIOR HOMME NEW EDT',
        precio:64400,
    },
    {
        id:9,
        imagen:'./images/dior/miss-dior-rose-n-roses-edt.webp',
        marca:'Dior',
        flanker:'MISS DIOR ROSE N ROSES EDT',
        precio:52600,
    },
    {
        id:10,
        imagen:'./images/dior/sauvage-elixir-edp.webp',
        marca:'Dior',
        flanker:'SAUVAGE ELIXIR EDP',
        precio:71500,
    },
    {
        id:11,
        imagen:'./images/dior/farenheit-edt.webp',
        marca:'Dior',
        flanker:'FAHRENHEIT EDP',
        precio:49600,
    },
    {
        id:12,
        imagen:'./images/dior/jadore-parfum-deau-edp.webp',
        marca:'Dior',
        flanker:'JADORE PARFUM DEAU EDP',
        precio:60100,
    },
    {
        id:13,
        imagen:'./images/dior/homme-cologne.webp',
        marca:'Dior',
        flanker:'DIOR HOMME COLOGNE',
        precio:68200,
    },
    {
        id:14,
        imagen:'./images/dior/homme-sport-edt.webp',
        marca:'Dior',
        flanker:'DIOR HOMME SPORT EDT',
        precio:49600,
    },
    {
        id:15,
        imagen:'./images/dior/miss-dior-edt.webp',
        marca:'Dior',
        flanker:'MISS DIOR EDT',
        precio:41100,
    },
    {
        id:16,
        imagen:'./images/dior/sauvage-edp-ed-limitada.webp',
        marca:'Dior',
        flanker:'SAUVAGE EDP ED. LIMITADA',
        precio:89100,
    },
    {
        id:17,
        imagen:'./images/dior/addict-edp.webp',
        marca:'Dior',
        flanker:'DIOR ADDICT EDP',
        precio:60100,
    },
    {
        id:18,
        imagen:'./images/dior/sauvage-after-shave-balm.webp',
        marca:'Dior',
        flanker:'SAUVAGE AFTER SHAVE BALM',
        precio:26200,
    },
    {
        id:19,
        imagen:'./images/dior/addict-eau-fraiche-edt.webp',
        marca:'Dior',
        flanker:'DIOR ADDICT EAU FRAICHE EDT',
        precio:52600,
    },
    {
        id:20,
        imagen:'./images/dior/roller-pearl-edp.webp',
        marca:'Dior',
        flanker:'MISS DIOR ROLLER PEARL EDP',
        precio:29000,
    }
];

const givenchyArray=[
    {
        id:1,
        imagen:'./images/givenchy/blue-label-edt.webp',
        marca:'Givenchy',
        flanker:'BLUE LABEL EDT',
        precio:43700,
    },
    {
        id:2,
        imagen:'./images/givenchy/linterditRougeEdp.webp',
        marca:'Givenchy',
        flanker:'LINTERDIT ROUGE EDP',
        precio:54600,
    },
    {
        id:3,
        imagen:'./images/givenchy/dayRichCream.webp',
        marca:'Givenchy',
        flanker:'L INTEMPOREL DAY RICH CREAM',
        precio:69100,
    },
    {
        id:4,
        imagen:'./images/givenchy/gentleman-reserve-privee-edp.webp',
        marca:'Givenchy',
        flanker:'GENTLEMAN RESERVE PRIVEE EDP',
        precio:50200,
    },
    {
        id:5,
        imagen:'./images/givenchy/ange-ou-demon-edp.webp',
        marca:'Givenchy',
        flanker:'ANGE OU DEMON EDP',
        precio:56200,
    },
    {
        id:6,
        imagen:'./images/givenchy/l-interdit-edt.webp',
        marca:'Givenchy',
        flanker:'LINTERDIT EDT',
        precio:44900,
    },
    {
        id:7,
        imagen:'./images/givenchy/biphasic-serum.webp',
        marca:'Givenchy',
        flanker:'LINTEMPOREL BIPHASIC SERUM',
        precio:69100,
    },
    {
        id:8,
        imagen:'./images/givenchy/blanc-divin-cream.webp',
        marca:'Givenchy',
        flanker:'BLANC DIVIN CREAM',
        precio:39200,
    },
    {
        id:9,
        imagen:'./images/givenchy/l-interdit-edp.webp',
        marca:'Givenchy',
        flanker:'LINTERDIT EDP',
        precio:53000,
    },
    {
        id:10,
        imagen:'./images/givenchy/ange-ou-demon-le-secret-edp.webp',
        marca:'Givenchy',
        flanker:'ANGE OU DEMON LE SECRET EDP',
        precio:56200,
    },
    {
        id:11,
        imagen:'./images/givenchy/irresistible-edp.webp',
        marca:'Givenchy',
        flanker:'IRRESISTIBLE EDP',
        precio:53000,
    }
];

const muglerArray=[
    {
        id:1,
        imagen:'./images/mugler/angelnova.webp',
        marca:'Mugler',
        flanker:'ANGEL NOVA EDP RECARGABLE',
        precio:79510,
    },
    {
        id:2,
        imagen:'./images/mugler/aliengoddess.webp',
        marca:'Mugler',
        flanker:'ALIEN GODDESS EDP REFILLIABLE',
        precio:47040,
    },
    {
        id:3,
        imagen:'./images/mugler/amenrubber.webp',
        marca:'Mugler',
        flanker:'A MEN RUBBER EDT RECARGABLE',
        precio:54150,
    },
    {
        id:4,
        imagen:'./images/mugler/alienrecargable.webp',
        marca:'Mugler',
        flanker:'ALIEN EDP RECARGABLE',
        precio:79600,
    },
    {
        id:5,
        imagen:'./images/mugler/angelnovarecargagle.webp',
        marca:'Mugler',
        flanker:'ANGEL NOVA EDT RECARGABLE',
        precio:50910,
    },
    {
        id:6,
        imagen:'./images/mugler/mugleredp.webp',
        marca:'Mugler',
        flanker:'ALIEN EDP',
        precio:61070,
    },
    {
        id:7,
        imagen:'./images/mugler/alienmanrecargable.webp',
        marca:'Mugler',
        flanker:'ALIEN MAN EDT RECARGABLE',
        precio:54130,
    }
];
